=== vanderbr/rates/schemas/v1/actuarial-table-h.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/vanderbr/rates/main/schemas/v1/actuarial-table-h.schema.json",
  "title": "actuarial-table-h",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "age",
      "dx_scaled_1e6",
      "nx_scaled_1e6",
      "mx_scaled_1e6"
    ],
    "properties": {
      "age": {
        "type": "integer",
        "minimum": 0
      },
      "dx_scaled_1e6": {
        "type": "integer",
        "minimum": 0
      },
      "nx_scaled_1e6": {
        "type": "integer",
        "minimum": 0
      },
      "mx_scaled_1e6": {
        "type": "integer",
        "minimum": 0
      }
    }
  }
}

=== vanderbr/rates/actuarial/table-h/by-interest-rate/00140-basis-points.json
[
  {
    "age": 0,
    "dx_scaled_1e6": 100000000000,
    "nx_scaled_1e6": 4675394000000,
    "mx_scaled_1e6": 34544490000
  },
  {
    "age": 1,
    "dx_scaled_1e6": 98010140000,
    "nx_scaled_1e6": 4577079000000,
    "mx_scaled_1e6": 33931030000
  },
  {
    "age": 2,
    "dx_scaled_1e6": 96616950000,
    "nx_scaled_1e6": 4480442000000,
    "mx_scaled_1e6": 33890760000
  },
  {
    "age": 3,
    "dx_scaled_1e6": 95256740000,
    "nx_scaled_1e6": 4385172000000,
    "mx_scaled_1e6": 33864330000
  },
  {
    "age": 4,
    "dx_scaled_1e6": 93921620000,
    "nx_scaled_1e6": 4291241000000,
    "mx_scaled_1e6": 33844250000
  },
  {
    "age": 5,
    "dx_scaled_1e6": 92609700000,
    "nx_scaled_1e6": 4198623000000,
    "mx_scaled_1e6": 33828970000
  },
  {
    "age": 6,
    "dx_scaled_1e6": 91317350000,
    "nx_scaled_1e6": 4107299000000,
    "mx_scaled_1e6": 33815170000
  },
  {
    "age": 7,
    "dx_scaled_1e6": 90044570000,
    "nx_scaled_1e6": 4017249000000,
    "mx_scaled_1e6": 33803090000
  },
  {
    "age": 8,
    "dx_scaled_1e6": 88790770000,
    "nx_scaled_1e6": 3928453000000,
    "mx_scaled_1e6": 33792430000
  },
  {
    "age": 9,
    "dx_scaled_1e6": 87555670000,
    "nx_scaled_1e6": 3840892000000,
    "mx_scaled_1e6": 33783180000
  },
  {
    "age": 10,
    "dx_scaled_1e6": 86338930000,
    "nx_scaled_1e6": 3754549000000,
    "mx_scaled_1e6": 33775240000
  },
  {
    "age": 11,
    "dx_scaled_1e6": 85139810000,
    "nx_scaled_1e6": 3669406000000,
    "mx_scaled_1e6": 33768130000
  },
  {
    "age": 12,
    "dx_scaled_1e6": 83956850000,
    "nx_scaled_1e6": 3585445000000,
    "mx_scaled_1e6": 33760610000
  },
  {
    "age": 13,
    "dx_scaled_1e6": 82787860000,
    "nx_scaled_1e6": 3502653000000,
    "mx_scaled_1e6": 33750720000
  },
  {
    "age": 14,
    "dx_scaled_1e6": 81630370000,
    "nx_scaled_1e6": 3421015000000,
    "mx_scaled_1e6": 33736160000
  },
  {
    "age": 15,
    "dx_scaled_1e6": 80482780000,
    "nx_scaled_1e6": 3340522000000,
    "mx_scaled_1e6": 33715470000
  },
  {
    "age": 16,
    "dx_scaled_1e6": 79344820000,
    "nx_scaled_1e6": 3261164000000,
    "mx_scaled_1e6": 33688520000
  },
  {
    "age": 17,
    "dx_scaled_1e6": 78216780000,
    "nx_scaled_1e6": 3182931000000,
    "mx_scaled_1e6": 33655750000
  },
  {
    "age": 18,
    "dx_scaled_1e6": 77098570000,
    "nx_scaled_1e6": 3105813000000,
    "mx_scaled_1e6": 33617190000
  },
  {
    "age": 19,
    "dx_scaled_1e6": 75990060000,
    "nx_scaled_1e6": 3029801000000,
    "mx_scaled_1e6": 33572850000
  },
  {
    "age": 20,
    "dx_scaled_1e6": 74891250000,
    "nx_scaled_1e6": 2954885000000,
    "mx_scaled_1e6": 33522860000
  },
  {
    "age": 21,
    "dx_scaled_1e6": 73801680000,
    "nx_scaled_1e6": 2881055000000,
    "mx_scaled_1e6": 33466900000
  },
  {
    "age": 22,
    "dx_scaled_1e6": 72721680000,
    "nx_scaled_1e6": 2808303000000,
    "mx_scaled_1e6": 33405440000
  },
  {
    "age": 23,
    "dx_scaled_1e6": 71652880000,
    "nx_scaled_1e6": 2736618000000,
    "mx_scaled_1e6": 33340230000
  },
  {
    "age": 24,
    "dx_scaled_1e6": 70597480000,
    "nx_scaled_1e6": 2665987000000,
    "mx_scaled_1e6": 33273660000
  },
  {
    "age": 25,
    "dx_scaled_1e6": 69557020000,
    "nx_scaled_1e6": 2596398000000,
    "mx_scaled_1e6": 33207450000
  },
  {
    "age": 26,
    "dx_scaled_1e6": 68531810000,
    "nx_scaled_1e6": 2527833000000,
    "mx_scaled_1e6": 33142150000
  },
  {
    "age": 27,
    "dx_scaled_1e6": 67521290000,
    "nx_scaled_1e6": 2460280000000,
    "mx_scaled_1e6": 33077380000
  },
  {
    "age": 28,
    "dx_scaled_1e6": 66524970000,
    "nx_scaled_1e6": 2393723000000,
    "mx_scaled_1e6": 33012850000
  },
  {
    "age": 29,
    "dx_scaled_1e6": 65542020000,
    "nx_scaled_1e6": 2328149000000,
    "mx_scaled_1e6": 32947940000
  },
  {
    "age": 30,
    "dx_scaled_1e6": 64571770000,
    "nx_scaled_1e6": 2263544000000,
    "mx_scaled_1e6": 32882150000
  },
  {
    "age": 31,
    "dx_scaled_1e6": 63613680000,
    "nx_scaled_1e6": 2199897000000,
    "mx_scaled_1e6": 32815120000
  },
  {
    "age": 32,
    "dx_scaled_1e6": 62667520000,
    "nx_scaled_1e6": 2137196000000,
    "mx_scaled_1e6": 32746780000
  },
  {
    "age": 33,
    "dx_scaled_1e6": 61733110000,
    "nx_scaled_1e6": 2075428000000,
    "mx_scaled_1e6": 32677120000
  },
  {
    "age": 34,
    "dx_scaled_1e6": 60810390000,
    "nx_scaled_1e6": 2014582000000,
    "mx_scaled_1e6": 32606230000
  },
  {
    "age": 35,
    "dx_scaled_1e6": 59899080000,
    "nx_scaled_1e6": 1954648000000,
    "mx_scaled_1e6": 32534010000
  },
  {
    "age": 36,
    "dx_scaled_1e6": 58998480000,
    "nx_scaled_1e6": 1895612000000,
    "mx_scaled_1e6": 32459910000
  },
  {
    "age": 37,
    "dx_scaled_1e6": 58107690000,
    "nx_scaled_1e6": 1837466000000,
    "mx_scaled_1e6": 32383160000
  },
  {
    "age": 38,
    "dx_scaled_1e6": 57225920000,
    "nx_scaled_1e6": 1780201000000,
    "mx_scaled_1e6": 32303110000
  },
  {
    "age": 39,
    "dx_scaled_1e6": 56352330000,
    "nx_scaled_1e6": 1723807000000,
    "mx_scaled_1e6": 32219040000
  },
  {
    "age": 40,
    "dx_scaled_1e6": 55485950000,
    "nx_scaled_1e6": 1668277000000,
    "mx_scaled_1e6": 32130080000
  },
  {
    "age": 41,
    "dx_scaled_1e6": 54626170000,
    "nx_scaled_1e6": 1613604000000,
    "mx_scaled_1e6": 32035720000
  },
  {
    "age": 42,
    "dx_scaled_1e6": 53772020000,
    "nx_scaled_1e6": 1559782000000,
    "mx_scaled_1e6": 31935080000
  },
  {
    "age": 43,
    "dx_scaled_1e6": 52921970000,
    "nx_scaled_1e6": 1506806000000,
    "mx_scaled_1e6": 31826690000
  },
  {
    "age": 44,
    "dx_scaled_1e6": 52074570000,
    "nx_scaled_1e6": 1454673000000,
    "mx_scaled_1e6": 31709150000
  },
  {
    "age": 45,
    "dx_scaled_1e6": 51228920000,
    "nx_scaled_1e6": 1403381000000,
    "mx_scaled_1e6": 31581590000
  },
  {
    "age": 46,
    "dx_scaled_1e6": 50385180000,
    "nx_scaled_1e6": 1352927000000,
    "mx_scaled_1e6": 31444200000
  },
  {
    "age": 47,
    "dx_scaled_1e6": 49543380000,
    "nx_scaled_1e6": 1303311000000,
    "mx_scaled_1e6": 31297030000
  },
  {
    "age": 48,
    "dx_scaled_1e6": 48702550000,
    "nx_scaled_1e6": 1254530000000,
    "mx_scaled_1e6": 31139130000
  },
  {
    "age": 49,
    "dx_scaled_1e6": 47861340000,
    "nx_scaled_1e6": 1206584000000,
    "mx_scaled_1e6": 30969170000
  },
  {
    "age": 50,
    "dx_scaled_1e6": 47018710000,
    "nx_scaled_1e6": 1159474000000,
    "mx_scaled_1e6": 30786070000
  },
  {
    "age": 51,
    "dx_scaled_1e6": 46174080000,
    "nx_scaled_1e6": 1113203000000,
    "mx_scaled_1e6": 30589250000
  },
  {
    "age": 52,
    "dx_scaled_1e6": 45327730000,
    "nx_scaled_1e6": 1067771000000,
    "mx_scaled_1e6": 30378940000
  },
  {
    "age": 53,
    "dx_scaled_1e6": 44480070000,
    "nx_scaled_1e6": 1023180000000,
    "mx_scaled_1e6": 30155550000
  },
  {
    "age": 54,
    "dx_scaled_1e6": 43631620000,
    "nx_scaled_1e6": 979430800000,
    "mx_scaled_1e6": 29919590000
  },
  {
    "age": 55,
    "dx_scaled_1e6": 42782440000,
    "nx_scaled_1e6": 936524900000,
    "mx_scaled_1e6": 29671090000
  },
  {
    "age": 56,
    "dx_scaled_1e6": 41931960000,
    "nx_scaled_1e6": 894463100000,
    "mx_scaled_1e6": 29409470000
  },
  {
    "age": 57,
    "dx_scaled_1e6": 41079210000,
    "nx_scaled_1e6": 853247000000,
    "mx_scaled_1e6": 29133760000
  },
  {
    "age": 58,
    "dx_scaled_1e6": 40223500000,
    "nx_scaled_1e6": 812879200000,
    "mx_scaled_1e6": 28843190000
  },
  {
    "age": 59,
    "dx_scaled_1e6": 39364370000,
    "nx_scaled_1e6": 773362900000,
    "mx_scaled_1e6": 28537290000
  },
  {
    "age": 60,
    "dx_scaled_1e6": 38501670000,
    "nx_scaled_1e6": 734701600000,
    "mx_scaled_1e6": 28215850000
  },
  {
    "age": 61,
    "dx_scaled_1e6": 37635080000,
    "nx_scaled_1e6": 696899100000,
    "mx_scaled_1e6": 27878500000
  },
  {
    "age": 62,
    "dx_scaled_1e6": 36764190000,
    "nx_scaled_1e6": 659959200000,
    "mx_scaled_1e6": 27524760000
  },
  {
    "age": 63,
    "dx_scaled_1e6": 35888400000,
    "nx_scaled_1e6": 623886700000,
    "mx_scaled_1e6": 27153990000
  },
  {
    "age": 64,
    "dx_scaled_1e6": 35006360000,
    "nx_scaled_1e6": 588687100000,
    "mx_scaled_1e6": 26764740000
  },
  {
    "age": 65,
    "dx_scaled_1e6": 34115860000,
    "nx_scaled_1e6": 554367700000,
    "mx_scaled_1e6": 26354720000
  },
  {
    "age": 66,
    "dx_scaled_1e6": 33213700000,
    "nx_scaled_1e6": 520938400000,
    "mx_scaled_1e6": 25920560000
  },
  {
    "age": 67,
    "dx_scaled_1e6": 32296530000,
    "nx_scaled_1e6": 488412600000,
    "mx_scaled_1e6": 25458750000
  },
  {
    "age": 68,
    "dx_scaled_1e6": 31365180000,
    "nx_scaled_1e6": 456804700000,
    "mx_scaled_1e6": 24969910000
  },
  {
    "age": 69,
    "dx_scaled_1e6": 30418350000,
    "nx_scaled_1e6": 426129400000,
    "mx_scaled_1e6": 24452540000
  },
  {
    "age": 70,
    "dx_scaled_1e6": 29457860000,
    "nx_scaled_1e6": 396401300000,
    "mx_scaled_1e6": 23908240000
  },
  {
    "age": 71,
    "dx_scaled_1e6": 28481850000,
    "nx_scaled_1e6": 367634800000,
    "mx_scaled_1e6": 23334960000
  },
  {
    "age": 72,
    "dx_scaled_1e6": 27488760000,
    "nx_scaled_1e6": 339846100000,
    "mx_scaled_1e6": 22730910000
  },
  {
    "age": 73,
    "dx_scaled_1e6": 26475580000,
    "nx_scaled_1e6": 313053700000,
    "mx_scaled_1e6": 22092830000
  },
  {
    "age": 74,
    "dx_scaled_1e6": 25441010000,
    "nx_scaled_1e6": 287278200000,
    "mx_scaled_1e6": 21419120000
  },
  {
    "age": 75,
    "dx_scaled_1e6": 24383800000,
    "nx_scaled_1e6": 262541400000,
    "mx_scaled_1e6": 20708230000
  },
  {
    "age": 76,
    "dx_scaled_1e6": 23306610000,
    "nx_scaled_1e6": 238864500000,
    "mx_scaled_1e6": 19962510000
  },
  {
    "age": 77,
    "dx_scaled_1e6": 22206380000,
    "nx_scaled_1e6": 216268900000,
    "mx_scaled_1e6": 19178610000
  },
  {
    "age": 78,
    "dx_scaled_1e6": 21085690000,
    "nx_scaled_1e6": 194776200000,
    "mx_scaled_1e6": 18358820000
