=== vanderbr/rates/schemas/v1/actuarial-table-z.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/vanderbr/rates/main/schemas/v1/actuarial-table-z.schema.json",
  "title": "actuarial-table-z",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "age",
      "udx_scaled_1e6",
      "unx_scaled_1e6",
      "umx_scaled_1e6"
    ],
    "properties": {
      "age": {
        "type": "integer",
        "minimum": 0
      },
      "udx_scaled_1e6": {
        "type": "integer",
        "minimum": 0
      },
      "unx_scaled_1e6": {
        "type": "integer",
        "minimum": 0
      },
      "umx_scaled_1e6": {
        "type": "integer",
        "minimum": 0
      }
    }
  }
}

=== vanderbr/rates/actuarial/table-z/by-interest-rate/01980-basis-points.json
[
  {
    "age": 0,
    "udx_scaled_1e6": 10000000000000000,
    "unx_scaled_1e6": 40243803512000000,
    "umx_scaled_1e6": 64497387000000
  },
  {
    "age": 1,
    "udx_scaled_1e6": 7970458856000000,
    "unx_scaled_1e6": 32248574084000000,
    "umx_scaled_1e6": 8840815000000
  },
  {
    "age": 2,
    "udx_scaled_1e6": 6389663148000000,
    "unx_scaled_1e6": 25857588509000000,
    "umx_scaled_1e6": 5869476000000
  },
  {
    "age": 3,
    "udx_scaled_1e6": 5123098480000000,
    "unx_scaled_1e6": 20733784347000000,
    "umx_scaled_1e6": 4283891000000
  },
  {
    "age": 4,
    "udx_scaled_1e6": 4107852877000000,
    "unx_scaled_1e6": 16625495418000000,
    "umx_scaled_1e6": 3304133000000
  },
  {
    "age": 5,
    "udx_scaled_1e6": 3293958175000000,
    "unx_scaled_1e6": 13331267326000000,
    "umx_scaled_1e6": 2697663000000
  },
  {
    "age": 6,
    "udx_scaled_1e6": 2641357966000000,
    "unx_scaled_1e6": 10689711116000000,
    "umx_scaled_1e6": 2252229000000
  },
  {
    "age": 7,
    "udx_scaled_1e6": 2118086957000000,
    "unx_scaled_1e6": 8571483093000000,
    "umx_scaled_1e6": 1935271000000
  },
  {
    "age": 8,
    "udx_scaled_1e6": 1698503260000000,
    "unx_scaled_1e6": 6872878593000000,
    "umx_scaled_1e6": 1707797000000
  },
  {
    "age": 9,
    "udx_scaled_1e6": 1362056719000000,
    "unx_scaled_1e6": 5510750426000000,
    "umx_scaled_1e6": 1547262000000
  },
  {
    "age": 10,
    "udx_scaled_1e6": 1092269748000000,
    "unx_scaled_1e6": 4418430808000000,
    "umx_scaled_1e6": 1435209000000
  },
  {
    "age": 11,
    "udx_scaled_1e6": 875927674000000,
    "unx_scaled_1e6": 3542466802000000,
    "umx_scaled_1e6": 1353576000000
  },
  {
    "age": 12,
    "udx_scaled_1e6": 702431541000000,
    "unx_scaled_1e6": 2840004034000000,
    "umx_scaled_1e6": 1283412000000
  },
  {
    "age": 13,
    "udx_scaled_1e6": 563283254000000,
    "unx_scaled_1e6": 2276687359000000,
    "umx_scaled_1e6": 1208320000000
  },
  {
    "age": 14,
    "udx_scaled_1e6": 451673147000000,
    "unx_scaled_1e6": 1824974200000000,
    "umx_scaled_1e6": 1118420000000
  },
  {
    "age": 15,
    "udx_scaled_1e6": 362149451000000,
    "unx_scaled_1e6": 1462778543000000,
    "umx_scaled_1e6": 1014598000000
  },
  {
    "age": 16,
    "udx_scaled_1e6": 290345927000000,
    "unx_scaled_1e6": 1172383650000000,
    "umx_scaled_1e6": 904577100000
  },
  {
    "age": 17,
    "udx_scaled_1e6": 232760590000000,
    "unx_scaled_1e6": 939574638000000,
    "umx_scaled_1e6": 795778700000
  },
  {
    "age": 18,
    "udx_scaled_1e6": 186581307000000,
    "unx_scaled_1e6": 752946988000000,
    "umx_scaled_1e6": 691651000000
  },
  {
    "age": 19,
    "udx_scaled_1e6": 149551557000000,
    "unx_scaled_1e6": 603352106000000,
    "umx_scaled_1e6": 594304400000
  },
  {
    "age": 20,
    "udx_scaled_1e6": 119860905000000,
    "unx_scaled_1e6": 483451479000000,
    "umx_scaled_1e6": 505053900000
  },
  {
    "age": 21,
    "udx_scaled_1e6": 96056120000000,
    "unx_scaled_1e6": 387359196000000,
    "umx_scaled_1e6": 423800200000
  },
  {
    "age": 22,
    "udx_scaled_1e6": 76972401000000,
    "unx_scaled_1e6": 310354491000000,
    "umx_scaled_1e6": 351216900000
  },
  {
    "age": 23,
    "udx_scaled_1e6": 61676123000000,
    "unx_scaled_1e6": 248650497000000,
    "umx_scaled_1e6": 288594300000
  },
  {
    "age": 24,
    "udx_scaled_1e6": 49417977000000,
    "unx_scaled_1e6": 199209383000000,
    "umx_scaled_1e6": 236607900000
  },
  {
    "age": 25,
    "udx_scaled_1e6": 39595792000000,
    "unx_scaled_1e6": 159594878000000,
    "umx_scaled_1e6": 194562400000
  },
  {
    "age": 26,
    "udx_scaled_1e6": 31725803000000,
    "unx_scaled_1e6": 127854064000000,
    "umx_scaled_1e6": 160834700000
  },
  {
    "age": 27,
    "udx_scaled_1e6": 25419880000000,
    "unx_scaled_1e6": 102422077000000,
    "umx_scaled_1e6": 133631100000
  },
  {
    "age": 28,
    "udx_scaled_1e6": 20367124000000,
    "unx_scaled_1e6": 82045143000000,
    "umx_scaled_1e6": 111590000000
  },
  {
    "age": 29,
    "udx_scaled_1e6": 16318386000000,
    "unx_scaled_1e6": 65718734000000,
    "umx_scaled_1e6": 93561760000
  },
  {
    "age": 30,
    "udx_scaled_1e6": 13074117000000,
    "unx_scaled_1e6": 52638002000000,
    "umx_scaled_1e6": 78699870000
  },
  {
    "age": 31,
    "udx_scaled_1e6": 10474481000000,
    "unx_scaled_1e6": 42158041000000,
    "umx_scaled_1e6": 66386320000
  },
  {
    "age": 32,
    "udx_scaled_1e6": 8391447000000,
    "unx_scaled_1e6": 33762051000000,
    "umx_scaled_1e6": 56177280000
  },
  {
    "age": 33,
    "udx_scaled_1e6": 6722407000000,
    "unx_scaled_1e6": 27035877000000,
    "umx_scaled_1e6": 47714360000
  },
  {
    "age": 34,
    "udx_scaled_1e6": 5385137000000,
    "unx_scaled_1e6": 21647623000000,
    "umx_scaled_1e6": 40711290000
  },
  {
    "age": 35,
    "udx_scaled_1e6": 4313715000000,
    "unx_scaled_1e6": 17331326000000,
    "umx_scaled_1e6": 34908820000
  },
  {
    "age": 36,
    "udx_scaled_1e6": 3455290000000,
    "unx_scaled_1e6": 13873881000000,
    "umx_scaled_1e6": 30066980000
  },
  {
    "age": 37,
    "udx_scaled_1e6": 2767512000000,
    "unx_scaled_1e6": 11104554000000,
    "umx_scaled_1e6": 25989010000
  },
  {
    "age": 38,
    "udx_scaled_1e6": 2216466000000,
    "unx_scaled_1e6": 8886549000000,
    "umx_scaled_1e6": 22530170000
  },
  {
    "age": 39,
    "udx_scaled_1e6": 1774976000000,
    "unx_scaled_1e6": 7110258000000,
    "umx_scaled_1e6": 19575730000
  },
  {
    "age": 40,
    "udx_scaled_1e6": 1421268000000,
    "unx_scaled_1e6": 5687858000000,
    "umx_scaled_1e6": 17033660000
  },
  {
    "age": 41,
    "udx_scaled_1e6": 1137905000000,
    "unx_scaled_1e6": 4548977000000,
    "umx_scaled_1e6": 14840880000
  },
  {
    "age": 42,
    "udx_scaled_1e6": 910906800000,
    "unx_scaled_1e6": 3637224000000,
    "umx_scaled_1e6": 12938770000
  },
  {
    "age": 43,
    "udx_scaled_1e6": 729064500000,
    "unx_scaled_1e6": 2907418000000,
    "umx_scaled_1e6": 11272990000
  },
  {
    "age": 44,
    "udx_scaled_1e6": 583402000000,
    "unx_scaled_1e6": 2323362000000,
    "umx_scaled_1e6": 9803846000
  },
  {
    "age": 45,
    "udx_scaled_1e6": 466734300000,
    "unx_scaled_1e6": 1856051000000,
    "umx_scaled_1e6": 8507273000
  },
  {
    "age": 46,
    "udx_scaled_1e6": 373310100000,
    "unx_scaled_1e6": 1482235000000,
    "umx_scaled_1e6": 7371651000
  },
  {
    "age": 47,
    "udx_scaled_1e6": 298514100000,
    "unx_scaled_1e6": 1183281000000,
    "umx_scaled_1e6": 6382351000
  },
  {
    "age": 48,
    "udx_scaled_1e6": 238640000000,
    "unx_scaled_1e6": 944256900000,
    "umx_scaled_1e6": 5519198000
  },
  {
    "age": 49,
    "udx_scaled_1e6": 190716700000,
    "unx_scaled_1e6": 753203900000,
    "umx_scaled_1e6": 4763616000
  },
  {
    "age": 50,
    "udx_scaled_1e6": 152365600000,
    "unx_scaled_1e6": 600543700000,
    "umx_scaled_1e6": 4101669000
  },
  {
    "age": 51,
    "udx_scaled_1e6": 121682100000,
    "unx_scaled_1e6": 478604100000,
    "umx_scaled_1e6": 3523014000
  },
  {
    "age": 52,
    "udx_scaled_1e6": 97141490000,
    "unx_scaled_1e6": 381238800000,
    "umx_scaled_1e6": 3020198000
  },
  {
    "age": 53,
    "udx_scaled_1e6": 77520860000,
    "unx_scaled_1e6": 303524600000,
    "umx_scaled_1e6": 2585855000
  },
  {
    "age": 54,
    "udx_scaled_1e6": 61839620000,
    "unx_scaled_1e6": 241518900000,
    "umx_scaled_1e6": 2212749000
  },
  {
    "age": 55,
    "udx_scaled_1e6": 49310950000,
    "unx_scaled_1e6": 192065800000,
    "umx_scaled_1e6": 1893210000
  },
  {
    "age": 56,
    "udx_scaled_1e6": 39303860000,
    "unx_scaled_1e6": 152640200000,
    "umx_scaled_1e6": 1619634000
  },
  {
    "age": 57,
    "udx_scaled_1e6": 31312990000,
    "unx_scaled_1e6": 121222800000,
    "umx_scaled_1e6": 1385165000
  },
  {
    "age": 58,
    "udx_scaled_1e6": 24934150000,
    "unx_scaled_1e6": 96199230000,
    "umx_scaled_1e6": 1184219000
  },
  {
    "age": 59,
    "udx_scaled_1e6": 19844050000,
    "unx_scaled_1e6": 76278600000,
    "umx_scaled_1e6": 1012179000
  },
  {
    "age": 60,
    "udx_scaled_1e6": 15784070000,
    "unx_scaled_1e6": 60429100000,
    "umx_scaled_1e6": 865162900
  },
  {
    "age": 61,
    "udx_scaled_1e6": 12547140000,
    "unx_scaled_1e6": 47826120000,
    "umx_scaled_1e6": 739688600
  },
  {
    "age": 62,
    "udx_scaled_1e6": 9967563000,
    "unx_scaled_1e6": 37810940000,
    "umx_scaled_1e6": 632692100
  },
  {
    "age": 63,
    "udx_scaled_1e6": 7912806000,
    "unx_scaled_1e6": 29857550000,
    "umx_scaled_1e6": 541491500
  },
  {
    "age": 64,
    "udx_scaled_1e6": 6276761000,
    "unx_scaled_1e6": 23546130000,
    "umx_scaled_1e6": 463626700
  },
  {
    "age": 65,
    "udx_scaled_1e6": 4974591000,
    "unx_scaled_1e6": 18541850000,
    "umx_scaled_1e6": 396926300
  },
  {
    "age": 66,
    "udx_scaled_1e6": 3938497000,
    "unx_scaled_1e6": 14577790000,
    "umx_scaled_1e6": 339490800
  },
  {
    "age": 67,
    "udx_scaled_1e6": 3114451000,
    "unx_scaled_1e6": 11441230000,
    "umx_scaled_1e6": 289807700
  },
  {
    "age": 68,
    "udx_scaled_1e6": 2459720000,
    "unx_scaled_1e6": 8962476000,
    "umx_scaled_1e6": 247038900
  },
  {
    "age": 69,
    "udx_scaled_1e6": 1939930000,
    "unx_scaled_1e6": 7006164000,
    "umx_scaled_1e6": 210228400
  },
  {
    "age": 70,
    "udx_scaled_1e6": 1527791000,
    "unx_scaled_1e6": 5464357000,
    "umx_scaled_1e6": 178735000
  },
  {
    "age": 71,
    "udx_scaled_1e6": 1201277000,
    "unx_scaled_1e6": 4251074000,
    "umx_scaled_1e6": 151759800
  },
  {
    "age": 72,
    "udx_scaled_1e6": 942849500,
    "unx_scaled_1e6": 3297937000,
    "umx_scaled_1e6": 128645400
  },
  {
    "age": 73,
    "udx_scaled_1e6": 738490900,
    "unx_scaled_1e6": 2550609000,
    "umx_scaled_1e6": 108789300
  },
  {
    "age": 74,
    "udx_scaled_1e6": 577093600,
    "unx_scaled_1e6": 1965928000,
    "umx_scaled_1e6": 91739910
  },
  {
    "age": 75,
    "udx_scaled_1e6": 449806500,
